language: ruby
rvm:
  - 1.9.3
  - 1.8.7
env:
  - DB_ADAPTER=postgresql DB_USER=postgres
  - DB_ADAPTER=sqlite3 DB_NAME=db/automigation
  - DB_ADAPTER=mysql2
script:
  - bundle exec rake db:prepare && bundle exec rspec
