development:
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql'%>
  database: <%= (ENV['DB_NAME'] || 'automigration') + (ENV['DB_ADAPTER'] == 'sqlite3' ? '.sqlite3' : '')%>
  user: <%= ENV['DB_USER'] %>

test:
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql'%>
  database: <%= (ENV['DB_NAME'] || 'automigration') + '_test' + (ENV['DB_ADAPTER'] == 'sqlite3' ? '.sqlite3' : '') %>
  user: <%= ENV['DB_USER'] %>

production:
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql'%>
  database: <%= (ENV['DB_NAME'] || 'automigration') + (ENV['DB_ADAPTER'] == 'sqlite3' ? '.sqlite3' : '')%>
  user: <%= ENV['DB_USER'] %>
